#pragma once

#define EE_HANDS

#define QUICK_TAP_TERM 120
#define TAPPING_TERM 180
#define TAPPING_TERM_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS
#define COMBO_TERM 40

#define MOUSE_EXTENDED_REPORT

#define PMW33XX_LIFTOFF_DISTANCE 0x03

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 4
